### ISSUE TITLE
The order of the menu items doesn't seem to follow the weight in drupal

### ISSUE THREAD

**Issue by shagel7984** [druxt/druxt-menu#31] opened 2020-10-15 11:59 UTC
**Describe the bug**
The order of the menu items doesn't seem to follow the weight in drupal.

**To Reproduce**
1. Go to drupal backend insert a new item in the main menu and set a weight. For me the new item is always the last item in druxt-menu. /jsonapi/menu_items/main shows the right order. 
Even clearing caches doesnt change the order.

**Comment by Decipher** [comment] 2020-10-16 01:27
Hi @shagel7984,

I tested this with myself and was unable to reproduce the issue.

My steps were:
Backend:
1. `git clone https://github.com/druxt/demo-api.druxtjs.org.git`
2. `cd demo-api.druxtjs.org`
3.

**Comment by Decipher** [comment] 2020-10-16 01:38
Hi @shagel7984,

I tested this with myself and was unable to reproduce the issue.

My steps were:

Setup backend:
1. `git clone https://github.com/druxt/demo-api.druxtjs.org.git`
2. `cd demo-api.druxtjs.org`
3. `docker-compose up -d`
4. `docker-compose exec cli bash`
5. `composer install`
6. `drush si -y demo_umami && drush -y en druxt jsonapi_views && drush rap anonymous 'access druxt resources'`
7. `drush uli`

Setup frontend:
1. `git clone https://github.com/druxt/demo.druxtjs.org`
2. `cd demo.druxtjs.org`
3. Edit `.env` and set `BASE_URL=http://demo-api-druxtjs-org.docker.amazee.io/`
4. `npm run dev`

Test:
1. Check menu is normal: http://localhost:3000
2. Add menu item: http://demo-api-druxtjs-org.docker.amazee.io/en/admin/structure/menu/manage/main/add?destination=/en/admin/structure/menu
  - Title: Test
  - Link: /node/1
3. Test new item is visible and positioned correctly: http://localhost:3000
4. Move menu item: http://demo-api-druxtjs-org.docker.amazee.io/en/admin/structure/menu/manage/main?destination=/en/admin/structure/menu
5. Test item is moved correctly: http://localhost:3000

Can you test and confirm?

**Comment by Decipher** [comment] 2021-08-14 05:42
I'm closing this issue as I was unable to reproduce the issue.

If you are still having issues, please re-open an issue in the https://github.com/druxt/druxt.js mono-repo

**Closed by Decipher** 2021-08-14 05:42 UTC
Labels: bug
